# Generated by Django 6.0.2 on 2026-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestregistration',
            name='unrated',
            field=models.BooleanField(default=False),
        ),
    ]
