# Generated by Django 6.0.2 on 2026-03-21 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestregistration_unrated'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_video', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='contesttestcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='contests.contestproblem'),
        ),
    ]
