# Generated by Django 6.0.2 on 2026-03-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_sitesetting_alter_contesttestcase_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='video_triggered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
