# Generated by Django 6.0.2 on 2026-03-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_sitesetting_video_triggered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='video_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
